mode: "dispatcher"
data-dir: "/data"
policy-dir: "/etc/blxrep/policies"
targets: 
  - "AWSDemo"
# Add user configuration for registration
name: "Vishnu ks"
email: "ksvishnu56@gmail.com"
organization: "appmend"
